packages:
  - docs
  - gui
  - packages/*
  - poc/*

allowBuilds:
  '@bufbuild/buf': true
  core-js: true
  esbuild: true

blockExoticSubdeps: false

patchedDependencies:
  mediabunny@1.58.1: patches/mediabunny@1.58.1.patch
