[package]
name = "chibitv_b60"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5"
bytes = "1.10.1"
chrono = "0.4.40"
julianday = "1.2.0"
strum = { version = "0.27.1", features = ["derive"] }
tracing = "0.1.41"
