import {
  CustomVideoDecoder,
  type EncodedPacket,
  type VideoCodec,
  VideoSample,
} from "mediabunny";

import type { FfmpegModule, FfmpegModuleFactory } from "./ffmpeg-module.js";

export class Mpeg2Decoder extends CustomVideoDecoder {
  private module: FfmpegModule | undefined;

  static override supports(codec: VideoCodec): boolean {
    return codec === "mpeg2";
  }

  override async init(): Promise<void> {
    // Generated by lib/build.sh and included in the published package.
    // @ts-expect-error The generated module is intentionally absent from the TypeScript source tree.
    const imported = (await import("../lib/dist/ffmpeg-mpeg2.js")) as {
      default: FfmpegModuleFactory;
    };
    this.module = await imported.default();

    const result = this.module._mpeg2_decoder_init();
    if (result < 0) {
      throw this.decoderError("mpeg2_decoder_init", result);
    }
  }

  override async decode(packet: EncodedPacket): Promise<void> {
    const module = this.requireModule();
    const pointer = module._malloc(packet.data.byteLength);
    if (pointer === 0) {
      throw new Error("Could not allocate packet memory in FFmpeg");
    }

    try {
      module.HEAPU8.set(packet.data, pointer);
      const result = module._mpeg2_decoder_send(
        pointer,
        packet.data.byteLength,
        packet.microsecondTimestamp,
        packet.microsecondDuration,
      );
      if (result < 0) {
        throw this.decoderError("mpeg2_decoder_send", result);
      }
    } finally {
      module._free(pointer);
    }

    this.emitAvailableFrames();
  }

  override async flush(): Promise<void> {
    const result = this.requireModule()._mpeg2_decoder_flush();
    if (result < 0) {
      throw this.decoderError("mpeg2_decoder_flush", result);
    }
    this.emitAvailableFrames();
  }

  override async close(): Promise<void> {
    this.module?._mpeg2_decoder_close();
    this.module = undefined;
  }

  private emitAvailableFrames(): void {
    const module = this.requireModule();
    while (module._mpeg2_decoder_receive() === 1) {
      const width = module._mpeg2_frame_width();
      const height = module._mpeg2_frame_height();
      const chromaWidth = Math.ceil(width / 2);
      const chromaHeight = Math.ceil(height / 2);
      const ySize = width * height;
      const chromaSize = chromaWidth * chromaHeight;
      const data = new Uint8Array(ySize + chromaSize * 2);

      this.copyPlane(data, 0, module._mpeg2_frame_plane_pointer(0), module._mpeg2_frame_plane_stride(0), width, height);
      this.copyPlane(
        data,
        ySize,
        module._mpeg2_frame_plane_pointer(1),
        module._mpeg2_frame_plane_stride(1),
        chromaWidth,
        chromaHeight,
      );
      this.copyPlane(
        data,
        ySize + chromaSize,
        module._mpeg2_frame_plane_pointer(2),
        module._mpeg2_frame_plane_stride(2),
        chromaWidth,
        chromaHeight,
      );

      const sarNum = module._mpeg2_frame_sar_num();
      const sarDen = module._mpeg2_frame_sar_den();
      const videoFrame = new VideoFrame(data, {
        format: "I420",
        codedWidth: width,
        codedHeight: height,
        displayWidth: this.config.displayAspectWidth ?? Math.round((width * sarNum) / sarDen),
        displayHeight: this.config.displayAspectHeight ?? height,
        timestamp: module._mpeg2_frame_pts(),
        duration: this.getFrameDuration(module),
        layout: [
          { offset: 0, stride: width },
          { offset: ySize, stride: chromaWidth },
          { offset: ySize + chromaSize, stride: chromaWidth },
        ],
        colorSpace: this.config.colorSpace,
      });
      this.onSample(new VideoSample(videoFrame));
    }
  }

  private copyPlane(
    destination: Uint8Array,
    destinationOffset: number,
    sourcePointer: number,
    sourceStride: number,
    rowBytes: number,
    rows: number,
  ): void {
    const module = this.requireModule();
    if (sourceStride === rowBytes) {
      destination.set(
        module.HEAPU8.subarray(sourcePointer, sourcePointer + rowBytes * rows),
        destinationOffset,
      );
      return;
    }

    for (let row = 0; row < rows; row++) {
      const sourceOffset = sourcePointer + row * sourceStride;
      destination.set(
        module.HEAPU8.subarray(sourceOffset, sourceOffset + rowBytes),
        destinationOffset + row * rowBytes,
      );
    }
  }

  private getFrameDuration(module: FfmpegModule): number | undefined {
    const duration = module._mpeg2_frame_duration();
    return duration > 0 ? duration : undefined;
  }

  private requireModule(): FfmpegModule {
    if (!this.module) {
      throw new Error("FFmpeg is not initialized");
    }
    return this.module;
  }

  private decoderError(operation: string, result: number): Error {
    const detail = this.module
      ? this.module.UTF8ToString(this.module._mpeg2_decoder_error())
      : "FFmpeg is not initialized";
    return new Error(`${operation} failed (${result}): ${detail}`);
  }
}
