[package]
name = "chibitv"
version = "0.1.0"
edition = "2024"

[dependencies]
chibitv_b60 = { path = "../chibitv_b60" }
chibitv_b61 = { path = "../chibitv_b61" }

anyhow = "1.0.97"
axum = { version = "0.8.3", features = ["macros"] }
bpaf = { version = "0.9.19", features = ["derive", "dull-color"] }
bytes = "1.10.1"
chrono = { version = "0.4.40", features = ["serde"] }
hex = "0.4.3"
http-body = "1.0.1"
http-body-util = "0.1.3"
mpeg2ts = "0.3.1"
openssl = "0.10.72"
papaya = "0.2.1"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.44.2", features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
utoipa = { version = "5.3.1", features = ["chrono"] }

[target.'cfg(unix)'.dependencies]
dvbv5-sys = { version = "0.2.1", optional = true }
libc = { version = "0.2.171", optional = true }

[features]
default = ["dvb"]
dvb = ["dep:dvbv5-sys", "dep:libc"]
