[package]
name = "chibitv_bon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
] }
